package com.thenogicode.dynamodbtest.dtos;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.thenogicode.dynamodbtest.converters.LocalDateTimeConverter;
import com.thenogicode.dynamodbtest.entities.SectionContent;
import com.thenogicode.dynamodbtest.enums.SectionStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SectionDto implements Serializable {

    private static final long serialVersionUID = -4051916190342255537L;

    private String id;
    private LocalDateTime dateCreated;
    private LocalDateTime dateModified;
    private SectionStatus status;
    private List<SectionContent> sectionContents;
    private int ageFrom;
    private int ageTo;

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String responseStatus;

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String exception;

    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String exceptionMessage;

}
