package com.thenogicode.dynamodbtest.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.thenogicode.dynamodbtest.converters.LocalDateTimeConverter;
import com.thenogicode.dynamodbtest.enums.ContentType;

import java.io.Serializable;
import java.time.LocalDateTime;

//@DynamoDBTable(tableName = "SectionContent")
public class SectionContent implements Serializable {

    private static final long serialVersionUID = -2795238222544631822L;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String sectionId;

    @DynamoDBAttribute
    private ContentType contentType;

    @DynamoDBAttribute
    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private LocalDateTime dateCreated;

    @DynamoDBAttribute
    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private LocalDateTime dateModified;

    @DynamoDBAttribute
    private int orderNo;

}
